{"uid":"46e290839b91d4c5","name":"User can login with valid credentials","fullName":"tests.test_selenium#test_login_success","historyId":"9e39a02a309f821ab1e87ebd74198990","time":{"start":1741899663798,"stop":1741899663798,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x55cfec3d546a <unknown>\n#1 0x55cfebe8eed0 <unknown>\n#2 0x55cfebec8c8f <unknown>\n#3 0x55cfebec468f <unknown>\n#4 0x55cfebf151cf <unknown>\n#5 0x55cfebf14706 <unknown>\n#6 0x55cfebf06633 <unknown>\n#7 0x55cfebed21be <unknown>\n#8 0x55cfebed3981 <unknown>\n#9 0x55cfec39b86b <unknown>\n#10 0x55cfec39f73c <unknown>\n#11 0x55cfec382f12 <unknown>\n#12 0x55cfec3a02b4 <unknown>\n#13 0x55cfec3670af <unknown>\n#14 0x55cfec3c3ad8 <unknown>\n#15 0x55cfec3c3cb6 <unknown>\n#16 0x55cfec3d42e6 <unknown>\n#17 0x7f795589caa4 <unknown>\n#18 0x7f7955929c3c <unknown>","statusTrace":"@pytest.fixture(autouse=True)\n    def driver():\n        os.makedirs(\"allure-results\", exist_ok=True)\n    \n        chrome_options = Options()\n        # chrome_options.add_argument(\"--headless\")\n        chrome_options.add_argument(\"--disable-gpu\")\n        chrome_options.add_argument(\"--window-size=1920,1080\")\n>       driver = webdriver.Chrome(options=chrome_options)\n\ntests/conftest.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:250: in __init__\n    self.start_session(capabilities)\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:342: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f91a6502350>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x55cfec3d42e6 \\\\u003Cunknown>\\\\n#17 0x7f795589caa4 \\\\u003Cunknown>\\\\n#18 0x7f7955929c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x55cfec3d546a <unknown>\nE       #1 0x55cfebe8eed0 <unknown>\nE       #2 0x55cfebec8c8f <unknown>\nE       #3 0x55cfebec468f <unknown>\nE       #4 0x55cfebf151cf <unknown>\nE       #5 0x55cfebf14706 <unknown>\nE       #6 0x55cfebf06633 <unknown>\nE       #7 0x55cfebed21be <unknown>\nE       #8 0x55cfebed3981 <unknown>\nE       #9 0x55cfec39b86b <unknown>\nE       #10 0x55cfec39f73c <unknown>\nE       #11 0x55cfec382f12 <unknown>\nE       #12 0x55cfec3a02b4 <unknown>\nE       #13 0x55cfec3670af <unknown>\nE       #14 0x55cfec3c3ad8 <unknown>\nE       #15 0x55cfec3c3cb6 <unknown>\nE       #16 0x55cfec3d42e6 <unknown>\nE       #17 0x7f795589caa4 <unknown>\nE       #18 0x7f7955929c3c <unknown>\n\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1741899655910,"stop":1741899655910,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"sensitive_url","time":{"start":1741899655910,"stop":1741899655910,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1741899655910,"stop":1741899655910,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1741899663799,"stop":1741899663998,"duration":199},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x55cfec3d546a <unknown>\n#1 0x55cfebe8eed0 <unknown>\n#2 0x55cfebec8c8f <unknown>\n#3 0x55cfebec468f <unknown>\n#4 0x55cfebf151cf <unknown>\n#5 0x55cfebf14706 <unknown>\n#6 0x55cfebf06633 <unknown>\n#7 0x55cfebed21be <unknown>\n#8 0x55cfebed3981 <unknown>\n#9 0x55cfec39b86b <unknown>\n#10 0x55cfec39f73c <unknown>\n#11 0x55cfec382f12 <unknown>\n#12 0x55cfec3a02b4 <unknown>\n#13 0x55cfec3670af <unknown>\n#14 0x55cfec3c3ad8 <unknown>\n#15 0x55cfec3c3cb6 <unknown>\n#16 0x55cfec3d42e6 <unknown>\n#17 0x7f795589caa4 <unknown>\n#18 0x7f7955929c3c <unknown>\n\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/sauce-labs-selenium-pytest/sauce-labs-selenium-pytest/tests/conftest.py\", line 21, in driver\n    driver = webdriver.Chrome(options=chrome_options)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"_skip_sensitive","time":{"start":1741899663799,"stop":1741899663799,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"suite","value":"Login"},{"name":"parentSuite","value":"Sauce Labs - Demo"},{"name":"host","value":"fv-az1712-414"},{"name":"thread","value":"2709-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_selenium"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"46e290839b91d4c5.json","parameterValues":[]}