{"uid":"d16d68fbe9e4d0de","name":"User can login with valid credentials","fullName":"tests.test_selenium#test_login_success","historyId":"9e39a02a309f821ab1e87ebd74198990","time":{"start":1741988477629,"stop":1741988477629,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x556f1b7ca46a <unknown>\n#1 0x556f1b283ed0 <unknown>\n#2 0x556f1b2bdc8f <unknown>\n#3 0x556f1b2b968f <unknown>\n#4 0x556f1b30a1cf <unknown>\n#5 0x556f1b309706 <unknown>\n#6 0x556f1b2fb633 <unknown>\n#7 0x556f1b2c71be <unknown>\n#8 0x556f1b2c8981 <unknown>\n#9 0x556f1b79086b <unknown>\n#10 0x556f1b79473c <unknown>\n#11 0x556f1b777f12 <unknown>\n#12 0x556f1b7952b4 <unknown>\n#13 0x556f1b75c0af <unknown>\n#14 0x556f1b7b8ad8 <unknown>\n#15 0x556f1b7b8cb6 <unknown>\n#16 0x556f1b7c92e6 <unknown>\n#17 0x7f12e689caa4 <unknown>\n#18 0x7f12e6929c3c <unknown>","statusTrace":"@pytest.fixture(autouse=True)\n    def driver():\n        os.makedirs(\"allure-results\", exist_ok=True)\n    \n        chrome_options = Options()\n        # chrome_options.add_argument(\"--headless\")\n        chrome_options.add_argument(\"--disable-gpu\")\n        chrome_options.add_argument(\"--window-size=1920,1080\")\n>       driver = webdriver.Chrome(options=chrome_options)\n\ntests/conftest.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:250: in __init__\n    self.start_session(capabilities)\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:342: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f2d68ffaea0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x556f1b7c92e6 \\\\u003Cunknown>\\\\n#17 0x7f12e689caa4 \\\\u003Cunknown>\\\\n#18 0x7f12e6929c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x556f1b7ca46a <unknown>\nE       #1 0x556f1b283ed0 <unknown>\nE       #2 0x556f1b2bdc8f <unknown>\nE       #3 0x556f1b2b968f <unknown>\nE       #4 0x556f1b30a1cf <unknown>\nE       #5 0x556f1b309706 <unknown>\nE       #6 0x556f1b2fb633 <unknown>\nE       #7 0x556f1b2c71be <unknown>\nE       #8 0x556f1b2c8981 <unknown>\nE       #9 0x556f1b79086b <unknown>\nE       #10 0x556f1b79473c <unknown>\nE       #11 0x556f1b777f12 <unknown>\nE       #12 0x556f1b7952b4 <unknown>\nE       #13 0x556f1b75c0af <unknown>\nE       #14 0x556f1b7b8ad8 <unknown>\nE       #15 0x556f1b7b8cb6 <unknown>\nE       #16 0x556f1b7c92e6 <unknown>\nE       #17 0x7f12e689caa4 <unknown>\nE       #18 0x7f12e6929c3c <unknown>\n\n../../../.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":3,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1741988476278,"stop":1741988476278,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1741988476278,"stop":1741988476278,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"sensitive_url","time":{"start":1741988476279,"stop":1741988476279,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1741988477629,"stop":1741988477830,"duration":201},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x556f1b7ca46a <unknown>\n#1 0x556f1b283ed0 <unknown>\n#2 0x556f1b2bdc8f <unknown>\n#3 0x556f1b2b968f <unknown>\n#4 0x556f1b30a1cf <unknown>\n#5 0x556f1b309706 <unknown>\n#6 0x556f1b2fb633 <unknown>\n#7 0x556f1b2c71be <unknown>\n#8 0x556f1b2c8981 <unknown>\n#9 0x556f1b79086b <unknown>\n#10 0x556f1b79473c <unknown>\n#11 0x556f1b777f12 <unknown>\n#12 0x556f1b7952b4 <unknown>\n#13 0x556f1b75c0af <unknown>\n#14 0x556f1b7b8ad8 <unknown>\n#15 0x556f1b7b8cb6 <unknown>\n#16 0x556f1b7c92e6 <unknown>\n#17 0x7f12e689caa4 <unknown>\n#18 0x7f12e6929c3c <unknown>\n\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/sauce-labs-selenium-pytest/sauce-labs-selenium-pytest/tests/conftest.py\", line 21, in driver\n    driver = webdriver.Chrome(options=chrome_options)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/sauce-labs-selenium-pytest-WbfEjJB0-py3.13/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"_skip_sensitive","time":{"start":1741988477629,"stop":1741988477629,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"suite","value":"Login"},{"name":"parentSuite","value":"Sauce Labs - Demo"},{"name":"host","value":"fv-az1279-995"},{"name":"thread","value":"2754-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_selenium"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"82e24f1ee7d70bfc","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x55f5ef3d346a <unknown>\n#1 0x55f5eee8ced0 <unknown>\n#2 0x55f5eeec6c8f <unknown>\n#3 0x55f5eeec268f <unknown>\n#4 0x55f5eef131cf <unknown>\n#5 0x55f5eef12706 <unknown>\n#6 0x55f5eef04633 <unknown>\n#7 0x55f5eeed01be <unknown>\n#8 0x55f5eeed1981 <unknown>\n#9 0x55f5ef39986b <unknown>\n#10 0x55f5ef39d73c <unknown>\n#11 0x55f5ef380f12 <unknown>\n#12 0x55f5ef39e2b4 <unknown>\n#13 0x55f5ef3650af <unknown>\n#14 0x55f5ef3c1ad8 <unknown>\n#15 0x55f5ef3c1cb6 <unknown>\n#16 0x55f5ef3d22e6 <unknown>\n#17 0x7f5becc9caa4 <unknown>\n#18 0x7f5becd29c3c <unknown>","time":{"start":1741988477391,"stop":1741988477391,"duration":0}},{"uid":"da4902d5eee7456","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x55b0c622546a <unknown>\n#1 0x55b0c5cdeed0 <unknown>\n#2 0x55b0c5d18c8f <unknown>\n#3 0x55b0c5d1468f <unknown>\n#4 0x55b0c5d651cf <unknown>\n#5 0x55b0c5d64706 <unknown>\n#6 0x55b0c5d56633 <unknown>\n#7 0x55b0c5d221be <unknown>\n#8 0x55b0c5d23981 <unknown>\n#9 0x55b0c61eb86b <unknown>\n#10 0x55b0c61ef73c <unknown>\n#11 0x55b0c61d2f12 <unknown>\n#12 0x55b0c61f02b4 <unknown>\n#13 0x55b0c61b70af <unknown>\n#14 0x55b0c6213ad8 <unknown>\n#15 0x55b0c6213cb6 <unknown>\n#16 0x55b0c62242e6 <unknown>\n#17 0x7f0573e9caa4 <unknown>\n#18 0x7f0573f29c3c <unknown>","time":{"start":1741988477098,"stop":1741988477098,"duration":0}},{"uid":"adf5ec85962431c8","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x55a79864d46a <unknown>\n#1 0x55a798106ed0 <unknown>\n#2 0x55a798140c8f <unknown>\n#3 0x55a79813c68f <unknown>\n#4 0x55a79818d1cf <unknown>\n#5 0x55a79818c706 <unknown>\n#6 0x55a79817e633 <unknown>\n#7 0x55a79814a1be <unknown>\n#8 0x55a79814b981 <unknown>\n#9 0x55a79861386b <unknown>\n#10 0x55a79861773c <unknown>\n#11 0x55a7985faf12 <unknown>\n#12 0x55a7986182b4 <unknown>\n#13 0x55a7985df0af <unknown>\n#14 0x55a79863bad8 <unknown>\n#15 0x55a79863bcb6 <unknown>\n#16 0x55a79864c2e6 <unknown>\n#17 0x7f050f29caa4 <unknown>\n#18 0x7f050f329c3c <unknown>","time":{"start":1741988476278,"stop":1741988476278,"duration":0}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":1,"unknown":0,"total":4},"items":[{"uid":"d8a7cb56528b4460","reportUrl":"https://MateoAgudGarcia.github.io/sauce-labs-selenium-pytest/17//#testresult/d8a7cb56528b4460","status":"passed","time":{"start":1741899814879,"stop":1741899815724,"duration":845}},{"uid":"33cd4cd11a12a5d4","reportUrl":"https://MateoAgudGarcia.github.io/sauce-labs-selenium-pytest/16//#testresult/33cd4cd11a12a5d4","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x564493c6046a <unknown>\n#1 0x564493719ed0 <unknown>\n#2 0x564493753c8f <unknown>\n#3 0x56449374f68f <unknown>\n#4 0x5644937a01cf <unknown>\n#5 0x56449379f706 <unknown>\n#6 0x564493791633 <unknown>\n#7 0x56449375d1be <unknown>\n#8 0x56449375e981 <unknown>\n#9 0x564493c2686b <unknown>\n#10 0x564493c2a73c <unknown>\n#11 0x564493c0df12 <unknown>\n#12 0x564493c2b2b4 <unknown>\n#13 0x564493bf20af <unknown>\n#14 0x564493c4ead8 <unknown>\n#15 0x564493c4ecb6 <unknown>\n#16 0x564493c5f2e6 <unknown>\n#17 0x7f3431a9caa4 <unknown>\n#18 0x7f3431b29c3c <unknown>","time":{"start":1741899664271,"stop":1741899664271,"duration":0}},{"uid":"bd80c2c7833898bd","reportUrl":"https://MateoAgudGarcia.github.io/sauce-labs-selenium-pytest/15//#testresult/bd80c2c7833898bd","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x56282b40846a <unknown>\n#1 0x56282aec1ed0 <unknown>\n#2 0x56282aefbc8f <unknown>\n#3 0x56282aef768f <unknown>\n#4 0x56282af481cf <unknown>\n#5 0x56282af47706 <unknown>\n#6 0x56282af39633 <unknown>\n#7 0x56282af051be <unknown>\n#8 0x56282af06981 <unknown>\n#9 0x56282b3ce86b <unknown>\n#10 0x56282b3d273c <unknown>\n#11 0x56282b3b5f12 <unknown>\n#12 0x56282b3d32b4 <unknown>\n#13 0x56282b39a0af <unknown>\n#14 0x56282b3f6ad8 <unknown>\n#15 0x56282b3f6cb6 <unknown>\n#16 0x56282b4072e6 <unknown>\n#17 0x7f80ed69caa4 <unknown>\n#18 0x7f80ed729c3c <unknown>","time":{"start":1741899480377,"stop":1741899480377,"duration":0}}]},"tags":[]},"source":"d16d68fbe9e4d0de.json","parameterValues":[]}